FROM tomcat:10.1.33
#RUN apt install mysql-server
#RUN mysql
#WORKDIR /opt/tomcat/webapps/
WORKDIR /app
COPY . /app
RUN mvn clean package
COPY target/springboot-thymeleaf-crud-web-app-0.0.1-SNAPSHOT.jar /opt/tomcat/webapps/
EXPOSE 8080
ENTRYPOINT ["java","-jar","springboot-thymeleaf-crud-web-app-0.0.1-SNAPSHOT.jar"]
